steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/main-composite-411800/cloudrun-nodejs:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/main-composite-411800/cloudrun-nodejs:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'main-composite-411800', '--region=us-central1', '--platform=managed', '--image=gcr.io/main-composite-411800/cloudrun-nodejs:$SHORT_SHA']
